// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCESX3q9c4zgawTjga_Yi87a7uoaf-jsZ0',
    appId: '1:531984402363:web:02e739af345f6977a6669e',
    messagingSenderId: '531984402363',
    projectId: 'listify-e896b',
    authDomain: 'listify-e896b.firebaseapp.com',
    storageBucket: 'listify-e896b.firebasestorage.app',
    measurementId: 'G-4XY5JVH12Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ7LOW_htHKxScSqkmhkXj_oWNrsNBO80',
    appId: '1:531984402363:android:6e2376b4b645e84da6669e',
    messagingSenderId: '531984402363',
    projectId: 'listify-e896b',
    storageBucket: 'listify-e896b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAleqjniE6ILGF71hoRv4dLaGT_OvgYNgQ',
    appId: '1:531984402363:ios:45c1142463da1c29a6669e',
    messagingSenderId: '531984402363',
    projectId: 'listify-e896b',
    storageBucket: 'listify-e896b.firebasestorage.app',
    androidClientId: '531984402363-0klcdcj613jbubfl3edll8gft8n5784j.apps.googleusercontent.com',
    iosClientId: '531984402363-tdlekclu717rqssg70bprn67phvl3nkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

}